# Generated by Django 5.1.1 on 2024-09-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
