# Generated by Django 5.1.1 on 2024-10-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Invoice_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoicemethod",
            name="payment_value",
        ),
    ]
