# Generated by Django 4.2.16 on 2024-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='acw',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='rate',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='total',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=30),
        ),
    ]
