# Generated by Django 5.1.1 on 2024-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(),
        ),
    ]
