# Generated by Django 4.2.16 on 2024-11-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0003_alter_paymentboqdetailed_acw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='nett_payment_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='progress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='acw',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='qty',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='paymentboqdetailed',
            name='total',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=30),
        ),
    ]
