# Generated by Django 4.2.16 on 2024-11-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0004_payment_nett_payment_due_payment_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='progress',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
