# Generated by Django 4.2.16 on 2024-11-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0005_alter_payment_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
