# Generated by Django 4.2.16 on 2024-11-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0006_alter_payment_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentboqdetailed',
            name='payment',
        ),
        migrations.AddField(
            model_name='paymentboqdetailed',
            name='project',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='boq_detailed', to='Invoice_app.project'),
            preserve_default=False,
        ),
    ]
