# Generated by Django 4.2.16 on 2024-11-20 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0007_remove_paymentboqdetailed_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='progress',
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_value', models.IntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='Invoice_app.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_category', to='Invoice_app.payment')),
            ],
        ),
    ]
