# Generated by Django 4.2.16 on 2024-11-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0008_remove_payment_payment_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to='Invoice_app.category')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to='Invoice_app.payment')),
            ],
        ),
        migrations.RemoveField(
            model_name='progress',
            name='payment',
        ),
        migrations.DeleteModel(
            name='PaymentCategory',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
    ]
