# Generated by Django 4.2.16 on 2024-11-20 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice_app', '0009_category_categoryprogress_remove_progress_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprogress',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to='Invoice_app.itemcategory'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
